apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    name: node-api-pod
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
spec:
  selector:
    matchLabels:
      name: node-api-pod
  template:
    metadata:
      labels:
        name: node-api-pod
    spec:
      containers:
      - name: node-api-container
        image: brianfive/simple-express-docker